---
language: ruby
notifications:
  email:
  - drbrain@segment7.net
rvm:
- 2.4
- 2.5
- 2.6
- 2.7
script: bundle exec rake test manifest:check

matrix:
  include:
  - rvm: "2.7"
    env: TRAVIS_MATRIX=pipeline
