name: Test

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7, '3.0', 3.1, 3.2, jruby-9.2]
        os: [ubuntu-20.04, windows-2022]
        include:
          - { ruby: 3.1, os: ubuntu-20.04, matrix: pipeline }

    runs-on: ${{ matrix.os }}

    env:
      CI_MATRIX: ${{ matrix.matrix }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Test things
      run: bundle exec rake test manifest:check
